# HAPPO parameters

algo_args:
  use_gae: True
  gamma: 0.99
  lambda: 1.0
  batch_episode: 10
  kl_coeff: 0.2
  num_sgd_iter: 10
  grad_clip: 10
  clip_param: 0.3
  critic_lr: 0.000001
  vf_loss_coeff: 1.0
  lr: 0.0001
  entropy_coeff: 0.01
  vf_clip_param: 10.0
  batch_mode: "complete_episodes"
  min_lr_schedule: 1e-11
  gain: 0.01
